# Generated by Django 3.2.8 on 2021-10-20 09:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlaneModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(20)])),
                ('model', models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(20)])),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1990), django.core.validators.MaxValueValidator(2021)])),
                ('weight', models.FloatField(validators=[django.core.validators.MinValueValidator(400), django.core.validators.MaxValueValidator(800)])),
                ('max_speed', models.IntegerField(validators=[django.core.validators.MinValueValidator(300), django.core.validators.MaxValueValidator(1000)])),
                ('seat_place', models.IntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(250)])),
            ],
            options={
                'verbose_name': 'planes',
                'verbose_name_plural': 'plane',
                'db_table': 'planes',
            },
        ),
    ]
